import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  BookOpen,
  BriefcaseMedical,
  Building2,
  CalendarCheck2,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ClipboardPlus,
  Clock3,
  CreditCard,
  Droplets,
  FileBadge2,
  FileCheck2,
  FileText,
  FolderHeart,
  HandCoins,
  HeartPulse,
  HelpCircle,
  House,
  Info,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  LockKeyhole,
  MapPin,
  Menu,
  MessageCircleMore,
  MonitorSmartphone,
  Moon,
  Navigation,
  NotebookPen,
  Phone,
  Pill,
  PlaneTakeoff,
  Plus,
  QrCode,
  ReceiptText,
  Route,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Stethoscope,
  Sun,
  Trash2,
  TriangleAlert,
  UserRound,
  UsersRound,
  Video,
  Wallet,
  X,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  bell: Bell,
  "building-2": Building2,
  building2: Building2,
  "calendar-check": CalendarCheck2,
  "calendar-days": CalendarDays,
  check: Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "clipboard-plus": ClipboardPlus,
  clock: Clock3,
  "circle-dot": BadgeCheck,
  droplet: Droplets,
  "file-check-2": FileCheck2,
  "file-text": FileText,
  "folder-heart": FolderHeart,
  "hand-coins": HandCoins,
  "heart-pulse": HeartPulse,
  house: House,
  info: Info,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "lock-keyhole": LockKeyhole,
  "map-pin": MapPin,
  menu: Menu,
  "messages-square": MessageCircleMore,
  mic: NotebookPen,
  monitor: MonitorSmartphone,
  moon: Moon,
  navigation: Navigation,
  phone: Phone,
  pill: Pill,
  "plane-takeoff": PlaneTakeoff,
  plus: Plus,
  "qr-code": QrCode,
  "receipt-text": ReceiptText,
  route: Route,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  stethoscope: Stethoscope,
  sun: Sun,
  trash: Trash2,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "user-round": UserRound,
  "users-round": UsersRound,
  video: Video,
  wallet: Wallet,
  x: X,
  "book-open": BookOpen,
  "briefcase-medical": BriefcaseMedical,
  "credit-card": CreditCard,
  "file-badge-2": FileBadge2,
  help: HelpCircle,
};

export function AppIcon({ name, size = 20, strokeWidth = 2, className = "" }) {
  const Icon = ICONS[name] || Activity;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />;
}
